### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <

### ISSUE THREAD

**Issue by twenzel** [RetireNet/dotnet-retire#55]
When I execute the CLI tool I get following exception:

```
❯ dotnet retire                                                                                                         info: dotnet_retire.RetireLogger[0]                                                                                           Scan starting                                                                                                     
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at dotnet_retire.HttpService.Get[T](Uri uri) in /Users/johnkors/koding/retirenet/dotnet-retire/dotnet-retire/Services/HttpService.cs:line 15
   at dotnet_retire.RetireApiClient.GetPackagesToRetire() in /Users/johnkors/koding/retirenet/dotnet-retire/dotnet-retire/Services/RetireApiClient.cs:line 21
   at dotnet_retire.RetireLogger.LogPackagesToRetire() in /Users/johnkors/koding/retirenet/dotnet-retire/dotnet-retire/Services/RetireLogger.cs:line 29
   at dotnet_retire.Program.Main(String[] args) in /Users/johnkors/koding/retirenet/dotnet-retire/dotnet-retire/Program.cs:line 9
```

**Comment by johnkors** [comment]
Could you provide a small sample repo as repro, and the working dir where you execute it?

**Comment by twenzel** [comment]
I cloned the repo and started to debug the tool project.

**Comment by johnkors** [comment]
Looks like you are getting a XML response from GitHub, maybe a temp glitch at GitHub?

**Comment by johnkors** [comment]
Any update?

**Comment by twenzel** [comment]
Yeah, it's an Proxy Auth Error (HTTP 407).
The `RetireNet.Packages.Tool.Services.HttpService.Get()` method does not check the HTTP status code of the response.

**Comment by johnkors** [comment]
Right, so you're running it from somewhere where there's a proxy in between you and GitHub..?

**Comment by twenzel** [comment]
Yep, we've a company proxy. It would be great to expose the error, so that users can handle it.

**Comment by johnkors** [comment]
Ok, nice. So what would the ideal output be in this case? "Cannot fetch vulnerable packages from source" + status code when trying to reach <url>..? Anything else?

**Comment by johnkors** [comment]
And how would a client of the tool handle it? Setup a rule in the proxy allowing githubusercontent.com requests? 



Another option is to to host the package feed yourself [and using this argument](https://github.com/RetireNet/dotnet-retire/blob/b642c5fd3b9a44446f343f10797a78994d3a7bdd/README.md#usage)t, but then you would have to sync with the packages repo regularly yourself.

```
$ dotnet retire --rooturl <URL_TO_YOUR_LOCAL_FEED> 
```

The default feed is https://raw.githubusercontent.com/RetireNet/Packages/master/index.json

**Comment by twenzel** [comment]
At least we should throw an exception (literally use `response.EnsureSuccessStatusCode()`) to inform the user of the tool what is going on.

Implementing new options to define a proxy that is used by the HTTPClient would be awesome. 
Or you can use the system proxy 
```
Client = new HttpClient(new WinHttpHandler() { WindowsProxyUsePolicy = WindowsProxyUsePolicy.UseWinInetProxy, DefaultProxyCredentials = CredentialCache.DefaultNetworkCredentials });
``` 
but that is platform-dependent.

**Comment by johnkors** [comment]
Sure! Would you like to do that in a PR?

**Comment by johnkors** [comment]
Closing due to inactivity.
