### ISSUE TITLE
Exception on mixed format solutions

### ISSUE THREAD

**Issue by johnkors** [RetireNet/dotnet-retire#61]
An exception is thrown on running `dotnet retire` when
* Running on a solution containing the old MSBuild style csprojs
* Running it on a MSbuild style csproj directly

```
$ dotnet retire
info: RetireNet.Packages.Tool.Services.RetireLogger[0]
      Scan starting

Unhandled Exception: RetireNet.Packages.Tool.Services.NoAssetsFoundException: Exception of type 'RetireNet.Packages.Tool.Services.NoAssetsFoundException' was thrown.
   at RetireNet.Packages.Tool.Services.FileService.ReadLockFiles() in /Users/johnkors/koding/retirenet/dotnet-retire/src/RetireNet.Packages.Tool/Services/FileService.cs:line 64
   at RetireNet.Packages.Tool.Services.RetireLogger.LogPackagesToRetire() in /Users/johnkors/koding/retirenet/dotnet-retire/src/RetireNet.Packages.Tool/Services/RetireLogger.cs:line 62
   at RetireNet.Packages.Tool.Program.Main(String[] args) in /Users/johnkors/koding/retirenet/dotnet-retire/src/RetireNet.Packages.Tool/Program.cs:line 9
```

**Comment by johnkors** [comment]
Proposal: Log old-style csprojs as a WARN: "Cannot analyze old-style csprojs"
